# .scrutinizer.yml

checks:
    php:
        code_rating: true
        duplication: true

    python:
        code_rating: true
        duplicate_code: true

    ruby:
        code_rating: true
        duplicate_code: true
build:
    tests:
        override:
            -
                environment:
                    'SCRUTINIZER_CC_FILE': 'my-coverage'
                coverage:
                    file: 'my-coverage'
                    format: 'rb-cc'
